#! /bin/sh

bspc config border_width 0
bspc config window_gap 12

bspc config top_padding 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d 1 2 3 4

xsetroot -cursor_name left_ptr &
compton --config /home/chris/.config/compton/compton.conf &
source /home/chris/.config/lemonbar/lemonbar &
source /home/chris/.config/fehbg
