#! /bin/sh

bspc config border_width 0
bspc config window_gap 10

#bspc config top_padding 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor LVDS1 -d 1 2 3 4
bspc monitor VGA1 -d 5 6 7 8

xsetroot -cursor_name left_ptr &
xsetroot -solid '#515151'
#compton --config /home/chris/.config/compton/compton.conf &
#source /home/chris/.config/lemonbar/lemonbar &
#source /home/chris/.config/fehbg
