#!/bin/sh

# Note that this expects the global stack to be able to compile xmonad
exec stack ghc -- \
     --make xmonad.hs \
     -i \
     -ilib \
     -fforce-recomp \
     -main-is main \
     -v0 \
     -o "$1"
