# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

###
# General Options
###

# Readline config
set -o vi

# Auto cd when a directory is entered
# e.g. /tmp -> cd /tmp
shopt -s autocd

# Immediately update bash history
shopt -s histappend
PROMPT_COMMAND="history -a; history -r; $PROMPT_COMMAND"

COMMAND_NOT_FOUND_HOOK=/usr/share/doc/pkgfile/command-not-found.bash
if [[ -e $COMMAND_NOT_FOUND_HOOK ]]; then
    source $COMMAND_NOT_FOUND_HOOK
fi

###
# Aliases
###

alias ls='ls --color=auto'
# fd is quite a bit easier to use
alias find='fd'


###
# Variables
###

export PS1='[$? \u@\h \W]\$ '
export HISTSIZE=100000
export VISUAL="emacsclient -a \"emacs --daemon\" -c"
# Editor should point to an editor that doesn't require "advanced" features e.g. ed, vi, etc
export EDITOR="vi -e"
export GIT_EDITOR="emacsclient -a \"emacs --daemon\" -c"
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

# Update path
export PATH="$PATH:$HOME/.emacs.d/bin"
export PATH="$PATH:$HOME/.local/bin"
